spring:
  application:
    name: resonance

  datasource:
    url: jdbc:postgresql://localhost:5432/resonance
    username: res
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

server:
  port: 8088